version: '3.0'

services:
    app:
        container_name: vue-petshop-client
        image: vue-petshop-client:dev
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 3003:8080
        volumes:
            - .:/project
            - /project/node_modules
